function Game()
	return ecs.Engine()
		:addEntity(createPlayer())
		:addSystem(DrawingSystem())
		:addSystem(VelocitySystem())
		:addSystem(GravitySystem())
		:addSystem(YFloorSystem(love.window.getHeight()))
		:addSystem(InputSystem())
		:addSystem(WalkingSystem())
end
